"""add timestamps and soft delete to all models

Revision ID: 78bbd4f0eb18
Revises: fdbbe1943d15
Create Date: 2026-01-18 05:57:45.782790

"""
from alembic import op
import sqlalchemy as sa


revision = '78bbd4f0eb18'
down_revision = 'fdbbe1943d15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add timestamp and soft delete columns to all tables
    # Use server_default for existing rows, then remove it
    
    # Invoices
    op.add_column('invoices', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('invoices', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('invoices', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.alter_column('invoices', 'created_at', server_default=None)
    op.alter_column('invoices', 'updated_at', server_default=None)
    
    # Payment Imputations
    op.add_column('payment_imputations', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('payment_imputations', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('payment_imputations', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.alter_column('payment_imputations', 'created_at', server_default=None)
    op.alter_column('payment_imputations', 'updated_at', server_default=None)
    
    # Payments
    op.add_column('payments', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('payments', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.alter_column('payments', 'created_at', server_default=None)
    op.alter_column('payments', 'updated_at', server_default=None)
    
    # Schools
    op.add_column('schools', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('schools', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('schools', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.alter_column('schools', 'created_at', server_default=None)
    op.alter_column('schools', 'updated_at', server_default=None)
    
    # Students
    op.add_column('students', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('students', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('students', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.alter_column('students', 'created_at', server_default=None)
    op.alter_column('students', 'updated_at', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'revoked_at')
    op.drop_column('students', 'updated_at')
    op.drop_column('students', 'created_at')
    op.drop_column('schools', 'revoked_at')
    op.drop_column('schools', 'updated_at')
    op.drop_column('schools', 'created_at')
    op.drop_column('payments', 'revoked_at')
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'created_at')
    op.drop_column('payment_imputations', 'revoked_at')
    op.drop_column('payment_imputations', 'updated_at')
    op.drop_column('payment_imputations', 'created_at')
    op.drop_column('invoices', 'revoked_at')
    op.drop_column('invoices', 'updated_at')
    op.drop_column('invoices', 'created_at')
    # ### end Alembic commands ###
